[~] Update github actions

diff --git a/template/.github/workflows/action.yml b/template/.github/workflows/action.yml
--- a/template/.github/workflows/action.yml
+++ b/template/.github/workflows/action.yml
@@ -9,16 +9,19 @@ env:
 jobs:
   check_coding_style:
     runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
+      - name: Launch coding style checker
+        run: check.sh $(pwd) $(pwd)
       - name: Check coding style
         run:
-          docker run --rm --security-opt "label:disable" -i -v "$(pwd)":"/mnt/delivery" -v "$(pwd)":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports" ;
           cat coding-style-reports.log;
           .github/workflows/display_coding_style
 
-  check_program_compilation:
+  check_program:
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker
@@ -29,31 +32,34 @@ jobs:
       - name: Launch "make"
         run: make
         timeout-minutes: 2
-      - name: Check banned functions
-        run: .github/workflows/check_banned_functions [project-exec] .github/workflows/authorized_functions.txt
       - name: Launch "make clean"
         run: make clean
       - name: Check program compilation
         run: .github/workflows/check_program_compilation ${{ env.EXECUTABLE }}
-
-  check_unit_tests:
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
-    needs: check_program_compilation
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.1.1
+      - name: Check banned functions
+        run: .github/workflows/check_banned_functions [project-exec] .github/workflows/authorized_functions.txt
       - name: Launch "make tests_run"
         run: make tests_run
         timeout-minutes: 2
+      - name: Check repository size
+        run: |
+          make fclean
+          size=$(du -sm --exclude='.git' | cut -f1)
+          limit=50
+          if [ "$size" -gt "$limit" ]; then
+            echo "::error title=Repository size::Repository size is too big ($size MB > $limit MB)"
+            exit 1
+          else
+            echo "::notice title=Repository size::Repository size is correct ($size MB <= $limit MB)"
+            exit 0
+          fi
 
   push_to_mirror:
     runs-on: ubuntu-latest
     if: |
       startsWith(github.ref, 'refs/heads/ga-ignore-') == false &&
       github.repository != '[git-ref]'
-    needs: check_unit_tests
+    needs: check_program
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
